### ISSUE TITLE
Design: how to store data in the BaseX database

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-core#10]
As developer 

I need to know how to store different database files in baseX

So I can integrate with openSCD

Background:

Is this way we want to store the the diffenent SCL files?

![image](https://user-images.githubusercontent.com/7427358/113730046-d20ba880-96f7-11eb-86bb-738996ecf850.png)

Acceptance criteria

-How to handle different file extensions?

-What are the relations and how to handle them?

-Document in the CoMPAS architecture including the requirements

**Comment by dlabordus** [comment]
There is e description in the CoMPAS Architecture about how different types are stored in BaseX. The drawing is also included.
The relations between them will be needed in others tools, like the SCT / OpenSCD.
