### ISSUE TITLE
Make artifacts available for other compas repositories

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-core#19]
There are now 2 repositories in which there is code that depends on classes from core-commons from compas-core repository. After pull requests are merged the artifact should be available for other parts of compas to be used. 

Where are think about https://docs.github.com/en/packages or maybe Maven Central to store there artifacts.

**Comment by Sander3003** [comment]
Please add documentation for others.

**Comment by dlabordus** [comment]
We are using Github packages and in the contribution there is a description about how to used these repositories in a Gradle build.
