### ISSUE TITLE
Generate JAVA code for multiple SCL version

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-core#25]
As a developer
I want support for all SCL versions of IEC61850
So I use all verions and make convertions between versions (where possible)

Background:
We want to support new verions and older verions.

Acceptance criteria:
-Use the CoMPAS XSD repository
-Store the generated java classes in a packege (per version) with 3 different package names
-re-use the naming scheme of the 61850 SCL standard

**Comment by Sander3003** [comment]
@legrosjf What is the status of this project? We missed you at the stand-up today ;) We need this as well for changes.

**Comment by dlabordus** [comment]
Hi @legrosjf, I did some work to generate the classes for all 3 versions in separate modules in the core, scl2003, scl2007b and scl2007b4. 
Also made MarshallerWrappers for all 3 versions with an abstract layer to reuse as much as possible.

**Comment by dlabordus** [comment]
Hi @legrosjf, 
The pull request is merged and we created a release with the new modules, 0.1.0.
These artifacts are in GitHub Packages, already using this version now in compas-cim-mapping.
