### ISSUE TITLE
How to handle company specific extensions

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-core#40]
Companies need some way to add their own specific extions to the SCL files.

Questions:
Where to store the XSD extensions?
How to validate the XSD extsions?
How to use them?

**Comment by dlabordus** [comment]
I think the most important part for now is the validator and there is a separate issue for that there (https://github.com/com-pas/compas-scl-validator/issues/116). 

No need to have it in the JAXB2 Converter for now. And that's maybe also possible if a custom config is used and a JAR file is added for the Company Specific generated classes, but that probably also means some kind of custom component build by the company itself.

So close it for now.
